version: '3'
services:
  nginx:
    build:
      dockerfile: nginx-prod.dockerfile
      context: docker
    image: oslo_config_remote_file_prod/nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - production-network
    depends_on:
      - flask1
      - flask2
      - flask3
  flask1:
    build:
      dockerfile: docker/flask-prod.dockerfile
      context: .
    image: oslo_config_remote_file_prod/flask
    container_name: flask1
    ports:
      - '5000'
    networks:
      - production-network
    depends_on:
      - mongodb
  flask2:
    build:
      dockerfile: docker/flask-prod.dockerfile
      context: .
    image: oslo_config_remote_file_prod/flask
    container_name: flask2
    ports:
      - '5000'
    networks:
      - production-network
    depends_on:
      - mongodb
  flask3:
    build:
      dockerfile: docker/flask-prod.dockerfile
      context: .
    image: oslo_config_remote_file_prod/flask
    container_name: flask3
    ports:
      - '5000'
    networks:
      - production-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    environment:
    - MONGO_DATA_DIR=/usr/data/db
    volumes:
      - ./data/db:/usr/data/db
    networks:
      - production-network
networks:
  production-network:
    driver: bridge
